apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: playground-skaffold
build:
  artifacts:
  - image: paritytech/substrate-playground-backend-api
    context: ../../backend
    docker:
      buildArgs:
        GITHUB_SHA: SKAFFOLD
  - image: paritytech/substrate-playground-backend-ui
    context: ../../frontend
    docker:
      buildArgs:
        GITHUB_SHA: SKAFFOLD
  local:
    useBuildkit: true
deploy:
  # See https://skaffold.dev/docs/pipeline-stages/deployers/kustomize/
  kustomize:
    buildArgs:
    - --enable-helm
    paths:
    - overlays/dev
