apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/environment: staging
  app.kubernetes.io/version: "1.0"

resources:
- ../../base

images:
- name: paritytech/substrate-playground-backend-api
  newTag: sha-cfab261c
- name: paritytech/substrate-playground-backend-ui
  newTag: sha-cfab261c

patches:
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: playground-staging.substrate.dev
  target:
    group: networking.k8s.io
    kind: Ingress
    name: ingress
    version: v1

patchesStrategicMerge:
- |-
  apiVersion: v1
  kind: Service
  metadata:
    name: v4-0-18-ingress-nginx-controller
    namespace: ingress-nginx
  spec:
    loadBalancerIP: 104.198.51.62
- |-
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: ingress
  spec:
    tls:
    - hosts:
      - '*.playground-staging.substrate.dev'
      secretName: playground-tls
