apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/environment: staging
  app.kubernetes.io/version: "1.0"

bases:
- ../../base

namespace: playground-staging

images:
- name: gcr.io/substrateplayground-252112/jeluard/substrate-playground
  digest: sha256:d95d40feca69098cf3e51c31a3bad67667db59c1e443c8664e14626bdf2b0536

patches:
- custom-load-balancer-ip.yaml

patchesJson6902:
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: ingress
  path: ingress-patch.yaml