apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/environment: staging
  app.kubernetes.io/version: "1.0"

namespace: playground-staging

resources:
- ../../base

images:
- name: gcr.io/substrateplayground-252112/jeluard/substrate-playground-backend-api
  digest: sha256:a6c091e9174eae38a08aa3553290f37f55522dafed0b318fc4b0fe9b18f46f29
- name: gcr.io/substrateplayground-252112/jeluard/substrate-playground-backend-ui
  digest: sha256:7d31998b984391a01f32ec32ac9a37baa02863d3f3f91b75397f9e0795fd33b2

patches:
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: playground-staging.substrate.dev
  target:
    group: extensions
    kind: Ingress
    name: ingress
    version: v1beta1

patchesStrategicMerge:
- |-
  apiVersion: v1
  kind: Service
  metadata:
    name: ingress-nginx
    namespace: ingress-nginx
  spec:
    loadBalancerIP: 34.69.4.59
- |-
  apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    name: ingress
  spec:
    tls:
    - hosts:
      - '*.playground-staging.substrate.dev'
      secretName: playground-tls
