version: "3.9"
services:
  openvscode:
    build:
      context: .
      dockerfile: Dockerfile-openvscode
    ports:
      - "3000:3000"
#    volumes:
#      - .:/code
#    environment:
#      FLASK_ENV: development
