[[bin]]
name = "playground"

[package]
name = "playground"
version = "0.1.0"
authors = ["jeluard <julien@parity.io>"]
edition = "2018"

[dependencies]
log = "0.4.14"
env_logger = "0.8.3"
prometheus = "0.11.0"
hyper = "0.14.2"
hyper-tls = "0.5.0"
json-patch = "0.2.6"
rocket = "0.4.7"
rocket_contrib = { version = "0.4.7", features = ["json"] }
rocket_cors = "0.5.2"
rocket_oauth2 = { version = "0.4.1", features = ["hyper_sync_rustls_adapter"] }
serde = { version = "1.0.123", features = ["derive"] }
serde_json = "1.0.61"
serde_yaml = "0.8.17"
kube = { version = "0.50.1", default-features = true, features = ["jsonpatch"] }
k8s-openapi = { version = "0.11.0", default-features = false, features = ["v1_15"] }
tokio = {version = "1.2.0", features = ["macros", "rt-multi-thread"] }
