[[bin]]
name = "playground"

[package]
name = "playground"
version = "0.1.0"
authors = ["jeluard <julien@parity.io>"]
edition = "2018"

[dependencies]
log = "0.4.8"
env_logger = "0.7.1"
uuid = { version = "0.8.1", features = ["v4"] }
prometheus = "0.8.0"
rocket = "0.4.4"
rocket_contrib = { version = "0.4.4", features = ["json"] }
rocket_cors = "0.5.2"
rocket_prometheus = "0.4.0"
serde = { version = "1.0.105", features = ["derive"] }
serde_json = "1.0.48"
serde_yaml = "0.8"
kube = "0.30.0"
k8s-openapi = { version = "0.7.1", default-features = false, features = ["v1_15"] }
tokio = {version = "0.2.17", features = ["macros"] }