[[bin]]
name = "playground"

[package]
name = "playground"
version = "0.1.0"
authors = ["jeluard <julien@parity.io>"]
edition = "2018"

[dependencies]
log = "0.4.13"
env_logger = "0.8.2"
prometheus = "0.11.0"
hyper = "0.10" #Do not update
hyper-sync-rustls = "=0.3.0-rc.17"
rocket = "0.4.6"
rocket_contrib = { version = "0.4.6", features = ["json"] }
rocket_cors = "0.5.2"
rocket_oauth2 = { version = "0.4.1", features = ["hyper_sync_rustls_adapter"] }
serde = { version = "1.0.120", features = ["derive"] }
serde_json = "1.0.61"
serde_yaml = "0.8.15"
kube = "0.47.0"
k8s-openapi = { version = "0.10.0", default-features = false, features = ["v1_15"] }
tokio = {version = "1.0.2", features = ["macros", "rt-multi-thread"] }
