[package]
name = "playground"
version = "0.1.0"
authors = ["jeluard <julien@parity.io>"]
edition = "2018"

[dependencies]
log = "0.4.14"
env_logger = "0.9.0"
prometheus = "0.12.0"
hyper = "0.14.11"
hyper-tls = "0.5.0"
json-patch = "0.2.6"
rocket = "0.4.10"
rocket_contrib = { version = "0.4.10", features = ["json"] }
rocket_cors = "0.5.2"
rocket_oauth2 = { version = "0.4.1", features = ["hyper_sync_rustls_adapter"] }
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
serde_yaml = "0.8.17"
kube = { version = "0.58.1", default-features = true, features = ["jsonpatch"] }
k8s-openapi = { version = "0.12.0", default-features = false, features = ["v1_16"] }
tokio = {version = "1.8.1", features = ["macros", "rt-multi-thread"] }
thiserror = "1.0"
