[package]
name = "playground"
version = "0.1.0"
authors = ["jeluard <julien@parity.io>"]
edition = "2018"

[dependencies]
log = "0.4.17"
env_logger = "0.9.0"
prometheus = "0.13.1"
hyper = "0.14.19"
hyper-tls = "0.5.0"
json-patch = "0.2.6"
rocket = "0.4.10"
rocket_contrib = { version = "0.4.10", features = ["json"] }
rocket_cors = "0.5.2"
rocket_oauth2 = { version = "0.4.1", features = ["hyper_sync_rustls_adapter"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
serde_yaml = "0.8.24"
kube = { version = "0.72.0", default-features = true, features = ["jsonpatch", "ws"] }
k8s-openapi = { version = "0.15.0", default-features = false, features = ["v1_23"] }
tokio = {version = "1.18.2", features = ["macros", "rt-multi-thread"] }
tokio-util = "0.7.2"
thiserror = "1.0.31"
git2 = "0.14.4"
clap = { version = "3.1.18", features = ["derive"] }
futures = "0.3"
