apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/environment: dev
  app.kubernetes.io/version: "1.0"

resources:
- ../../base

generatorOptions:
  disableNameSuffixHash: true

images:
- name: paritytech/substrate-playground-backend-api
  newTag: sha-b1733cf3
- name: paritytech/substrate-playground-backend-ui
  newTag: sha-b1733cf3

patches:
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: playground-dev.substrate.test
  target:
    group: networking.k8s.io
    kind: Ingress
    name: ingress
    version: v1
