apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/environment: dev
  app.kubernetes.io/version: "1.0"

namespace: default

resources:
- ../../base
- templates.yaml

images:
- name: paritytech/substrate-playground-backend-api
  newTag: latest
- name: paritytech/substrate-playground-backend-ui
  newTag: latest

patches:
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: playground-dev.substrate.test
  target:
    group: extensions
    kind: Ingress
    name: ingress
    version: v1beta1