apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/environment: dev
  app.kubernetes.io/version: "1.0"

resources:
- ../../base
- templates.yaml

images:
- name: paritytech/substrate-playground-backend-api
  newTag: latest
- name: paritytech/substrate-playground-backend-ui
  newTag: latest

patches:
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: playground-dev.substrate.test
  target:
    group: networking.k8s.io
    kind: Ingress
    name: ingress
    version: v1beta1

configMapGenerator:
  - name: config
    literals:
    - github.clientId=dd81163290c118582a1a

secretGenerator:
  - name: secrets
    literals:
    # Safe as it is used for a .test TLD (can't be registered)
    - github.clientSecret=abdcf38dd290429b98f43074d010b989cf970461
    - rocket.secretKey=tNxYqkQ5o9KiT8mQPVxqxu+H2Sl+Jd4CxkpFZmkw6Kw=