apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/environment: dev
  app.kubernetes.io/version: "1.0"

resources:
- ../../base

images:
- name: paritytech/substrate-playground-backend-api
  newTag: sha-000fd495
- name: paritytech/substrate-playground-backend-ui
  newTag: sha-000fd495

patches:
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: playground-dev.substrate.test
  target:
    group: networking.k8s.io
    kind: Ingress
    name: ingress
    version: v1

patchesStrategicMerge:
- |-
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: ingress
  spec:
    tls:
    - hosts:
      - '*.playground-dev.substrate.test'
      secretName: playground-tls
