apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- datasources.yaml
- deployment.yaml
- providers.yaml
- service.yaml
- volume.yaml
images:
- name: grafana/grafana
  newTag: 7.3.2

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: grafana-dashboards
  files:
  - dashboards/home.json
