apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api-deployment
  labels:
    app.kubernetes.io/component: backend-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: backend-api
  template:
    metadata:
      labels:
        app.kubernetes.io/component: backend-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      serviceAccountName: backend-service-account
      containers:
      - name: backend-api
        image: paritytech/substrate-playground-backend-api
        imagePullPolicy: IfNotPresent
        command: ["backend"]
        securityContext:
          privileged: false
          readOnlyRootFilesystem: true
          runAsUser: 10000
          runAsGroup: 10000
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
        ports:
        - containerPort: 8080
        env:
          # See https://rocket.rs/v0.4/guide/configuration/
          - name: ROCKET_ENV
            value: "staging"
          - name: ROCKET_PORT
            value: "8080"
          - name: ROCKET_LOG
            value: "normal"
          - name: ROCKET_ADDRESS
            value: "0.0.0.0"
          - name: GITHUB_CLIENT_ID
            valueFrom:
              configMapKeyRef:
                name: playground-config
                key: github.clientId
          - name: GITHUB_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: playground-secrets
                key: github.clientSecret
          - name: SESSION_DEFAULT_DURATION
            valueFrom:
              configMapKeyRef:
                name: playground-config
                key: session.defaultDuration
          - name: SESSION_MAX_DURATION
            valueFrom:
              configMapKeyRef:
                name: playground-config
                key: session.maxDuration
          - name: SESSION_DEFAULT_POOL_AFFINITY
            valueFrom:
              configMapKeyRef:
                name: playground-config
                key: session.defaultPoolAffinity
          - name: SESSION_DEFAULT_MAX_PER_NODE
            valueFrom:
              configMapKeyRef:
                name: playground-config
                key: session.defaultMaxPerNode
          - name: ROCKET_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: playground-secrets
                key: rocket.secretKey
        resources:
          requests:
            memory: "1Gi"
            cpu: "0.5"
          limits:
            memory: "2Gi"
            cpu: "1"
        readinessProbe:
          httpGet:
            path: /api
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 3600
---
apiVersion: v1
kind: Service
metadata:
  name: backend-api-service
spec:
  type: ClusterIP
  ports:
  - name: api-port
    port: 80
    targetPort: 8080
  selector:
    app.kubernetes.io/component: backend-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-service-account
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: backend-role
subjects:
- kind: ServiceAccount
  name: backend-service-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
