apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api-deployment
  labels:
    app.kubernetes.io/component: backend-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: backend-api
  template:
    metadata:
      labels:
        app.kubernetes.io/component: backend-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
    spec:
      serviceAccountName: default-service-account
      containers:
      - name: backend-api
        image: paritytech/substrate-playground-backend-api
        command: ["backend"]
        securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            runAsUser: 10001
            runAsGroup: 10001
        ports:
        - containerPort: 80
        env:
          # See https://rocket.rs/v0.4/guide/configuration/
          - name: ROCKET_ENV
            value: "staging"
          - name: ROCKET_PORT
            value: "80"
          - name: ROCKET_LOG
            value: "debug"
          - name: ROCKET_ADDRESS
            value: "0.0.0.0"
          - name: GITHUB_CLIENT_ID
            valueFrom:
              configMapKeyRef:
                name: playground-config
                key: github.clientId
          - name: GITHUB_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: playground-secrets
                key: github.clientSecret
          - name: WORKSPACE_BASE_IMAGE
            valueFrom:
              configMapKeyRef:
                name: playground-config
                key: workspace.baseImage
          - name: WORKSPACE_DEFAULT_DURATION
            valueFrom:
              configMapKeyRef:
                name: playground-config
                key: workspace.defaultDuration
          - name: WORKSPACE_MAX_DURATION
            valueFrom:
              configMapKeyRef:
                name: playground-config
                key: workspace.maxDuration
          - name: WORKSPACE_DEFAULT_POOL_AFFINITY
            valueFrom:
              configMapKeyRef:
                name: playground-config
                key: workspace.defaultPoolAffinity
          - name: WORKSPACE_DEFAULT_MAX_PER_NODE
            valueFrom:
              configMapKeyRef:
                name: playground-config
                key: workspace.defaultMaxPerNode
          - name: ROCKET_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: playground-secrets
                key: rocket.secretKey
        resources:
          requests:
            memory: "512Mi"
            cpu: "0.5"
          limits:
            memory: "1Gi"
            cpu: "0.75"
        readinessProbe:
          httpGet:
            path: /api
            port: 80
          initialDelaySeconds: 2
          periodSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: backend-api-service
spec:
  type: ClusterIP
  ports:
  - name: api-port
    port: 80
  selector:
    app.kubernetes.io/component: backend-api
