apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prepull-templates
spec:
  selector:
    matchLabels:
      name: prepull-templates
  template:
    metadata:
      labels:
        name: prepull-templates
    spec:
      initContainers:
        - name: node-template
          image: docker
          command: ["docker", "pull", "paritytech/substrate-playground-template-node-template-theia:sha-af065c19"]
          volumeMounts:
          - name: docker
            mountPath: /var/run
        - name: recipes
          image: docker
          command: ["docker", "pull", "paritytech/substrate-playground-template-recipes-theia:sha-9a27604"]
          volumeMounts:
          - name: docker
            mountPath: /var/run
      volumes:
        - name: docker
          hostPath:
            path: /var/run
      containers:
        - name: pause
          image: gcr.io/google_containers/pause
