apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/environment: production
  app.kubernetes.io/version: "1.0"

bases:
- ../../base

resources:
- resource-quota.yaml

namespace: playground

images:
- name: paritytech/substrate-playground-backend-api
  newTag: sha-ae6a78e
- name: paritytech/substrate-playground-backend-ui
  newTag: sha-ae6a78e

patches:
- custom-load-balancer-ip.yaml

patchesJson6902:
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: ingress
  path: ingress-patch.yaml