apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/environment: production
  app.kubernetes.io/version: "1.0"

bases:
- ../../base

resources:
- resource-quota.yaml

namespace: playground

images:
- name: gcr.io/substrateplayground-252112/jeluard/substrate-playground
  digest: sha256:b33808b4ecbb92fdad85aec909a1702600bebdd7aeb1f744c35f522d62be7a0b

patches:
- custom-load-balancer-ip.yaml

patchesJson6902:
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: ingress
  path: ingress-patch.yaml