apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/environment: production
  app.kubernetes.io/version: "1.0"

resources:
- ../../base
- resource-quota.yaml

images:
- name: paritytech/substrate-playground-backend-api
  newTag: sha-29f1451
- name: paritytech/substrate-playground-backend-ui
  newTag: sha-29f1451

patches:
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: playground.substrate.dev
  target:
    group: networking.k8s.io
    kind: Ingress
    name: ingress
    version: v1beta1

patchesStrategicMerge:
- |-
  apiVersion: v1
  kind: Service
  metadata:
    name: ingress-nginx-controller
    namespace: ingress-nginx
  spec:
    loadBalancerIP: 35.202.224.243
- |-
  apiVersion: networking.k8s.io/v1beta1
  kind: Ingress
  metadata:
    name: ingress
  spec:
    tls:
    - hosts:
      - '*.playground.substrate.dev'
      secretName: playground-tls
