apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    app.kubernetes.io/component: grafana
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: grafana
    spec:
      containers:
        - image: grafana/grafana
          name: grafana
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 500m
              memory: 2500Mi
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: GF_SECURITY_ALLOW_EMBEDDING
              value: "true"
            - name: GF_SERVER_SERVE_FROM_SUB_PATH
              value: "true"
            - name: GF_SERVER_ROOT_URL
              value: "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
            - name: GF_SERVER_STATIC_ROOT_PATH
              value: "public"
            - name: GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH
              value: "/etc/grafana/dashboards/home.json"
            - name: GF_AUTH_DISABLE_LOGIN_FORM
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
          volumeMounts:
          - name: grafana
            mountPath: /var/lib/grafana
          - name: dashboards
            mountPath: /etc/grafana/dashboards
          - name: datasources
            mountPath: /etc/grafana/provisioning/datasources
          - name: providers
            mountPath: /etc/grafana/provisioning/dashboards
      volumes:
      - name: grafana
        emptyDir: {}
      - name: dashboards
        configMap:
          name: grafana-dashboards
      - name: datasources
        configMap:
          name: grafana-datasources
      - name: providers
        configMap:
          name: grafana-providers