apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- datasources.yaml
- deployment.yaml
- providers.yaml
- service.yaml
images:
- name: grafana/grafana
  newTag: 7.1.5
configMapGenerator:
- name: grafana-dashboards
  files:
  - dashboards/home.json
  - dashboards/deployments.json