apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: playground-templates
  files:
    - ../../../../templates/ink
    - ../../../../templates/node-template
        - ../../../../templates/node-template-openvscode
    - ../../../../templates/front-end-template
    - ../../../../templates/parachain-template
    - ../../../../templates/recipes
