# See:
# * https://github.com/kubernetes/ingress-nginx/blob/main/docs/deploy/index.md#quick-start
# * https://github.com/kubernetes/ingress-nginx/tree/main/charts/ingress-nginx
#
# To update:

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx
helmCharts:
- name: ingress-nginx
  valuesInline:
    controller:
      extraArgs:
        default-ssl-certificate: "default/playground-tls"
      metrics:
        enabled: true
  releaseName: v4-0-18
  version: 4.0.18
  repo: https://kubernetes.github.io/ingress-nginx
