#
# Continuously tests node source code
#

name: Continuous Integration node

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[CI Skip]')"
    defaults:
      run:
        working-directory: ./${{ inputs.path }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install
        run: yarn install --check-files

      - name: Build
        run: yarn build

      - name: Lint
        if: hashFiles('.eslintrc.json') != ''
        run: yarn lint

      - name: Audit
        run: yarn audit
