# TODO
name: Continuous Build templates

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/10 * * * *' # Every 10 minutes

jobs:
  build-templates:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

# Iterate over all conf/templates
# For each:
#  - read repo id, last commit, branch from YAML
#  - fetch last commit from repo
#  - if different, co, build, push images, update YAML
#  - if not, ignore

# https://github.com/actions/github-script
# https://github.com/actions/toolkit
# https://github.com/octokit/action.js/
# https://github.com/actions/typescript-action
# https://stackoverflow.com/questions/59288971/retrieving-list-of-modified-files-in-github-action
# https://github.com/marketplace/actions/get-changed-files
# https://github.com/lots0logs/gh-action-get-changed-files
# https://github.com/jitterbit/get-changed-files

      - name: Set environment
        id: env
        run: |
          NAMESPACE=`grep NAMESPACE .env | cut -d '=' -f2`
          PROJECT=`grep GKE_PROJECT .env | cut -d '=' -f2`
          ZONE=`grep GKE_ZONE .env | cut -d '=' -f2`
          echo ::set-output name=namespace::$( echo ${NAMESPACE} )
          echo ::set-output name=project::$( echo ${PROJECT} )
          echo ::set-output name=zone::$( echo ${ZONE} )
          CLUSTER=`grep GKE_CLUSTER .env | cut -d '=' -f2`
          if [[ $GITHUB_REF == 'refs/heads/master' ]]; then
              echo ::set-output name=environment::production
              CLUSTER=`grep GKE_CLUSTER .env.production | cut -d '=' -f2`
          elif [[ $GITHUB_REF == 'refs/heads/develop' ]]; then
              echo ::set-output name=environment::staging
              CLUSTER='substrate-playground-staging'
          fi
          echo ::set-output name=cluster::$( echo ${CLUSTER} )
