name: Continuous Deployment Playground

on:
  push:
    branches:
      - develop
      - master
    paths-ignore:
      - 'README.md'
      - '.github/workflows/book.yml'
      - '.github/workflows/release.yml'
      - '.github/workflows/ci-**'
      - '.github/workflows/cd-base-templates.yml'
      - '.github/workflows/cd-templates.yml'
      - '.github/workflows/event-*'
      - '.github/workflows/templates/*'
      - '.github/workflow-templates/*'
      - 'docs/**'
      - 'conf/k8s/overlays/**/templates/**'
      - 'conf/k8s/overlays/production'
      - 'conf/k8s/overlays/dev'
      - 'templates/**'

env:
  GKE_PROJECT: gke_substrateplayground-252112
  GKE_ZONE: us-central1-a
  DOCKER_BUILDKIT: 1

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set env to staging
        if: endsWith(github.ref, '/develop')
        run: |
          echo "::set-env name=ENVIRONMENT::staging"
          echo "::set-env name=NAMESPACE::playground-staging"
          echo "::set-env name=GKE_CLUSTER::susbtrate-playground-staging"

      - name: Set env to production
        if: endsWith(github.ref, '/master')
        run: |
          echo "::set-env name=ENVIRONMENT::production"
          echo "::set-env name=NAMESPACE::playground"
          echo "::set-env name=GKE_CLUSTER::substrate-playground"

      - uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCLOUD_KEY }}
          export_default_credentials: true
          project_id: ${{ env.GKE_PROJECT }}
      - run: gcloud --quiet auth configure-docker
      - run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
      - run: echo "::set-env name=ACCESS_TOKEN::$(gcloud auth print-access-token)"

      - run: echo ::set-output name=sha::sha-${GITHUB_SHA::7}
        id: env

      - name: Prepare labels
        id: prep
        run: |
            VERSION=edge
            if [[ $GITHUB_REF == refs/tags/* ]]; then
              VERSION=${GITHUB_REF#refs/tags/}
            elif [[ $GITHUB_REF == refs/heads/* ]]; then
              VERSION=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
            elif [[ $GITHUB_REF == refs/pull/* ]]; then
              VERSION=pr-${{ github.event.number }}
            fi
            echo ::set-output name=version::${VERSION}
            echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')

      - name: Prepare labels paritytech/substrate-playground-backend-api
        id: prep-api
        run: |
            VERSION=edge
            if [[ $GITHUB_REF == refs/tags/* ]]; then
              VERSION=${GITHUB_REF#refs/tags/}
            elif [[ $GITHUB_REF == refs/heads/* ]]; then
              VERSION=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
            elif [[ $GITHUB_REF == refs/pull/* ]]; then
              VERSION=pr-${{ github.event.number }}
            fi
            DOCKER_IMAGE=paritytech/substrate-playground-backend-api
            TAGS="${DOCKER_IMAGE}:latest,${DOCKER_IMAGE}:${VERSION},${DOCKER_IMAGE}:sha-${GITHUB_SHA::7}"
            echo ::set-output name=tags::${TAGS}

      - name: Prepare labels paritytech/substrate-playground-backend-ui
        id: prep-ui
        run: |
            VERSION=edge
            if [[ $GITHUB_REF == refs/tags/* ]]; then
              VERSION=${GITHUB_REF#refs/tags/}
            elif [[ $GITHUB_REF == refs/heads/* ]]; then
              VERSION=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
            elif [[ $GITHUB_REF == refs/pull/* ]]; then
              VERSION=pr-${{ github.event.number }}
            fi
            DOCKER_IMAGE=paritytech/substrate-playground-backend-ui
            TAGS="${DOCKER_IMAGE}:latest,${DOCKER_IMAGE}:${VERSION},${DOCKER_IMAGE}:sha-${GITHUB_SHA::7}"
            echo ::set-output name=tags::${TAGS}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v2
        with:
          context: backend
          file: backend/Dockerfile
          build-args: GITHUB_SHA=${{ steps.env.outputs.sha }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.prep-api.outputs.tags }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.clone_url }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}

      - uses: docker/build-push-action@v2
        with:
          context: frontend
          file: frontend/Dockerfile
          build-args: GITHUB_SHA=${{ steps.env.outputs.sha }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.prep-ui.outputs.tags }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.clone_url }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv3.6.1/kustomize_v3.6.1_linux_amd64.tar.gz
          tar zxvf kustomize*
          chmod u+x ./kustomize  
        working-directory: conf/k8s/overlays/${{ env.ENVIRONMENT }}

      - name: Update version
        run: |-
          ./kustomize edit set image paritytech/substrate-playground-backend-api:${{ steps.env.outputs.sha }}
          ./kustomize edit set image paritytech/substrate-playground-backend-ui:${{ steps.env.outputs.sha }}
        working-directory: conf/k8s/overlays/${{ env.ENVIRONMENT }}

      - uses: EndBug/add-and-commit@v4
        with:
          message: ":bookmark: upon which, hails onto us a new release of Playground"
          add: "conf/k8s/overlays/${{ env.ENVIRONMENT }}/kustomization.yaml"
          tag: ${{ steps.env.outputs.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy on GKE
        run:  |-
          ./kustomize build . | kubectl apply --record -f -
          kubectl get services -o wide
        working-directory: conf/k8s/overlays/${{ env.ENVIRONMENT }}

      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v3
        with:
          urls: https://$NAMESPACE.substrate.dev/
          uploadArtifacts: true

      - uses: microsoft/playwright-github-action@v1

      - name: Run tests
        run: yarn && yarn test
        working-directory: ./e2e
        continue-on-error: true
        env:
          ENVIRONMENT: $ENVIRONMENT

      - if: ${{ failure() }}
        uses: s3krit/matrix-message-action@v0.0.3
        with:
          room_id: ${{ secrets.MATRIX_ROOM_ID }}
          access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
          message: "Integration tests failed"
          server: "matrix.parity.io"

      # TODO
      # if not ok, fails and rollback
      # https://learnk8s.io/kubernetes-rollbacks
      # https://medium.com/@copyconstruct/testing-in-production-the-safe-way-18ca102d0ef1
      - if: ${{ success() }}
        name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.env.outputs.sha }}-${{ env.ENVIRONMENT }}
          release_name: Release ${{ steps.env.outputs.sha }}
          body: |
            Backend release:
            - paritytech/substrate-playground-backend-api:${{ steps.env.outputs.sha }}
            - paritytech/substrate-playground-backend-ui:${{ steps.env.outputs.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}