# Deploy templates on playground as soon as changes are commited in conf/../templates/* files
name: Continuous Deployment templates

on:
  push:
    branches:
      - develop
      - master
    paths:
      - 'conf/k8s/overlays/*/templates/*'

env:
  GKE_PROJECT: gke_substrateplayground-252112
  GKE_ZONE: us-central1-a

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set env to staging
        if: endsWith(github.ref, '/develop')
        run: |
          echo "::set-env name=ENVIRONMENT::staging"
          echo "::set-env name=NAMESPACE::playground-staging"
          echo "::set-env name=GKE_CLUSTER::susbtrate-playground-staging"

      - name: Set env to production
        if: endsWith(github.ref, '/master')
        run: |
          echo "::set-env name=ENVIRONMENT::production"
          echo "::set-env name=NAMESPACE::playground"
          echo "::set-env name=GKE_CLUSTER::substrate-playground"

      - uses: actions/checkout@v2

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCLOUD_KEY }}
          export_default_credentials: true
          project_id: ${{ env.GKE_PROJECT }}
      - run: gcloud --quiet auth configure-docker
      - run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
      - run: echo "::set-env name=ACCESS_TOKEN::$(gcloud auth print-access-token)"

      - name: Deploy templates
        run: kubectl create configmap templates --namespace=${NAMESPACE} --from-file=conf/k8s/overlays/${ENVIRONMENT}/templates/ --dry-run=client -o yaml | kubectl apply -f -

# TODO test image, rollback commit if fails
# Do not rollback the rollback itself
# GITHUB_REF
# https://engineering.bitnami.com/articles/rolling-updates-for-configmap-objects.html