#
# Deploy templates on playground as soon as changes are commited in conf/../templates/* files
# Changes on branch 'develop' are deployed on staging, while changes on branch 'master' are deployed on production.
#
name: Continuous Deployment templates
# TODO only deploy if image has been updated?
on:
  push:
    branches:
      - develop
      - master
    paths:
      - 'conf/templates/*'
      - 'conf/k8s/overlays/*/templates/*'

jobs:
  push-templates:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Set environment
        id: env
        run: |
          NAMESPACE=`grep NAMESPACE .env | cut -d '=' -f2`
          GKE_PROJECT=`grep GKE_PROJECT .env | cut -d '=' -f2`
          GKE_ZONE=`grep GKE_ZONE .env | cut -d '=' -f2`
          if [[ $GITHUB_REF == 'refs/heads/master' ]]; then
              ENVIRONMENT='production'
          elif [[ $GITHUB_REF == 'refs/heads/develop' ]]; then
              ENVIRONMENT='staging'
          fi
          GKE_CLUSTER='substrate-playground-'${ENVIRONMENT}
          echo ::set-output name=environment::$( echo ${ENVIRONMENT} )
          echo ::set-output name=namespace::$( echo ${NAMESPACE} )
          echo ::set-output name=project::$( echo ${GKE_PROJECT} )
          echo ::set-output name=zone::$( echo ${GKE_ZONE} )
          echo ::set-output name=cluster::$( echo ${GKE_CLUSTER} )

      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCLOUD_KEY }}
          export_default_credentials: true
          project_id: ${{ steps.env.outputs.project }}
      - run: gcloud --quiet auth configure-docker
      - run: gcloud container clusters get-credentials "${{ steps.env.outputs.cluster }}" --zone "${{ steps.env.outputs.zone }}"

      - name: Deploy templates
        run: make k8s-update-templates-config
        env:
          ENV: ${{ steps.env.outputs.environment }}
          SKIP_ACK: true

# TODO test image, rollback commit if fails
# Do not rollback the rollback itself
# GITHUB_REF
# https://engineering.bitnami.com/articles/rolling-updates-for-configmap-objects.html
