# Deploy templates on playground as soon as changes are commited in conf/../templates/* files
name: Continuous Deployment templates

on:
  push:
    branches:
      - develop
      - master
    paths:
      - 'conf/k8s/overlays/*/templates/*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set env to staging
        if: endsWith(github.ref, '/develop')
        id: env
        run: |
          NAMESPACE=`grep NAMESPACE .env | cut -d '=' -f2`
          PROJECT=`grep PROJECT .env | cut -d '=' -f2`
          ZONE=`grep ZONE .env | cut -d '=' -f2`
          echo ::set-output name=namespace::$( echo ${NAMESPACE} )
          echo ::set-output name=project::$( echo ${PROJECT} )
          echo ::set-output name=zone::$( echo ${ZONE} )
          if [[ $GITHUB_REF == 'refs/heads/master' ]]; then
              echo ::set-output name=environment::production
              echo ::set-output name=cluster::substrate-playground
          else if [[ $GITHUB_REF == 'refs/heads/develop' ]]; then
              echo ::set-output name=environment::staging
              echo ::set-output name=cluster::susbtrate-playground-staging
          fi

      - uses: actions/checkout@v2

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCLOUD_KEY }}
          export_default_credentials: true
          project_id: ${{ steps.env.outputs.project }}
      - run: gcloud --quiet auth configure-docker
      - run: gcloud container clusters get-credentials "${{ steps.env.outputs.cluster }}" --zone "${{ steps.env.outputs.zone }}"

      - name: Deploy templates
        run: kubectl create configmap templates --namespace=${{ steps.env.outputs.namespace }} --from-file=conf/k8s/overlays/${{ steps.env.outputs.environment }}/templates/ --dry-run=client -o yaml | kubectl apply -f -

# TODO test image, rollback commit if fails
# Do not rollback the rollback itself
# GITHUB_REF
# https://engineering.bitnami.com/articles/rolling-updates-for-configmap-objects.html