#
# Continuously tests client source code
#

name: Continuous Integration client

on:
  push:
    branches:
      - develop
    paths:
      - '.github/workflows/ci-client.yml'
      - 'cli/**'
  pull_request:
    branches:
      - develop
    paths:
      - '.github/workflows/ci-client.yml'
      - 'cli/**'

jobs:
  build:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[CI Skip]')"
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install
        run: yarn install --check-files

      - name: Lint
        run: yarn lint
        continue-on-error: true

      - name: Audit
        run: yarn audit
        continue-on-error: true

      - name: Build
        run: yarn build
