#
# Continuously tests client source code
#

name: Continuous Integration client

on:
  push:
    branches:
      - develop
    paths:
      - '.github/workflows/ci-client.yml'
      - 'client/**'
  pull_request:
    branches:
      - develop
    paths:
      - '.github/workflows/ci-client.yml'
      - 'client/**'

jobs:
  build:
    uses: ./.github/workflows/base-ci-node.yml
    with:
      path: client
