#
# Continuously tests e2e source code
#

name: Continuous Integration e2e

on:
  push:
    branches:
      - develop
    paths:
      - '.github/workflows/ci-e2e.yml'
      - 'e2e/**'
  pull_request:
    branches:
      - develop
    paths:
      - '.github/workflows/ci-e2e.yml'
      - 'e2e/**'

jobs:
  build:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[CI Skip]')"
    defaults:
      run:
        working-directory: ./e2e
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install
        run: yarn install --check-files

      - name: Lint
        run: yarn lint
        continue-on-error: true

      - name: Audit
        run: yarn audit
        continue-on-error: true

      - name: Build
        run: yarn build
