name: Continuous Integration Playground

on:
  pull_request:
    paths-ignore:
      - 'templates/**'

jobs:
  frontend:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[CI Skip]')"
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v2
      # https://github.com/actions/setup-node
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Install
        run: yarn install --check-files
        working-directory: ./frontend
      - name: Lint
        run: yarn lint
        working-directory: ./frontend
      #- name: Audit
      #  run: yarn audit
      #  working-directory: ./frontend
      - name: Build
        run: yarn build
        working-directory: ./frontend

  backend:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[CI Skip]')"
    steps:
      # https://github.com/hecrj/setup-rust-action
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: nightly
          components: rustfmt, clippy
      - uses: actions/checkout@v2
      - name: Check Formatting
        run: cargo check-fmt
        working-directory: ./backend
      - name: Lint
        run: cargo lint
        working-directory: ./backend
      - name: Build
        run: cargo build --verbose
        working-directory: ./backend
      - name: Run tests
        run: cargo test --verbose
        working-directory: ./backend