name: Continuous Integration templates

on:
  pull_request:
    paths:
      - '.github/workflows/ci-templates.yml'
      - 'templates/*'

jobs:
  templates:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[CI Skip]')"
    defaults:
      run:
        working-directory: ./templates
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install
        run: yarn install --check-files

      - name: Build
        run: yarn workspace @parity/theia-playground theia build

      - uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Build Dockerfile.base
        run: docker build -f Dockerfile.base .

      - name: Build Dockerfile.theia-base
        run: docker build -f Dockerfile.theia-base .
