name: Continuous Integration

on: [pull_request]

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: yarn install --check-files
        working-directory: ./frontend
      - run: yarn lint
        working-directory: ./frontend
      - run: yarn audit
        working-directory: ./frontend
      - run: yarn build
        working-directory: ./frontend
  backend:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable]

    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
          components: rustfmt, clippy
      - uses: actions/checkout@master
      - name: Build
        run: cargo build --verbose
        working-directory: ./backend
      - name: Run tests
        run: cargo test --verbose
        working-directory: ./backend

  clippy:
    name: clippy (ubuntu-latest, stable)
    runs-on: ubuntu-latest
    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
          components: clippy
      - name: Checkout sources
        uses: actions/checkout@v1
      - name: Cargo Clippy
        run: cargo clippy -- -D warnings -A deprecated
        working-directory: ./backend

  fmt:
    name: fmt (ubuntu-latest, stable)
    runs-on: ubuntu-latest
    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
          components: rustfmt
      - name: Checkout sources
        uses: actions/checkout@v1
      - name: Check Formatting
        run: cargo fmt --all -- --check
        working-directory: ./backend