#
# Periodically polls latest repository commit for all templates.
# Update associated template metadata. This in turns triggers `cd-templates`.
#
name: Continuous Poll template repositories

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - '.github/workflows/cp-templates.yml'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 * * * *' # Every hour

jobs:
  list-existing-templates:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-templates.outputs.matrix }}
    steps:

      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install yq
        run: |
          python -m pip install --upgrade pip
          pip install yq

      - name: Set templates
        id: set-templates
        run: |
          JSON="{\"include\":["
          for FILE in "conf/templates"/*
          do
            REPOSITORY=`cat $FILE | yq -r .repository`
            REF=`cat $FILE | yq -r .ref`
            ID=${FILE##*/}
            JSONline="{\"id\": \"$ID\", \"repository\": \"$REPOSITORY\", \"ref\": \"$REF\"},"
            JSON="$JSON$JSONline"
          done
          JSON="$JSON]}"

          echo ::set-output name=matrix::$( echo "$JSON" )

  update-template-commit:
    needs: list-existing-templates
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.list-existing-templates.outputs.matrix)}}
      max-parallel: 1
    steps:

      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install yq
        run: |
          python -m pip install --upgrade pip
          pip install yq

      - uses: octokit/request-action@v2.x
        id: latest-commit
        with:
          route: GET /repos/${{ matrix.repository }}/commits/${{ matrix.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update template version
        run: |-
          FILE=conf/templates/${{ matrix.id }}
          TEMP=$(mktemp)
          cat $FILE | yq -y ".ref = \"${{ fromJson(steps.latest-commit.outputs.data).sha }}\"" > $TEMP && mv $TEMP $FILE

      - run: |
          if git status --porcelain | grep conf/templates/${{ matrix.id }}; then
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add conf/templates/${{ matrix.id }}
            git commit -m ":bookmark: yee shall thurst into an updated remote repository for ${{ matrix.id }}"
            git pull --rebase
            git push
          fi
