#
# Continuously tests (every 30 minutes) staging and production environment using e2e tests.
#
name: Continuous Testing playground

on:
  workflow_dispatch:
  pull_request:
    branches:
    - develop
    paths:
    - '.github/workflows/ct-playground.yml'
    - 'e2e/**'
  schedule:
    - cron:  '*/30 * * * *' # Every 30 minutes

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [staging, production]
      max-parallel: 1
    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop

      - name: Setup node
        uses: actions/setup-node@v3.0.0
        with:
          node-version: "16"

      - name: Set environment
        id: env
        run: |
          if [[ $ENV == 'production' ]]; then
              echo ::set-output name=domain::playground
          elif [[ $ENV == 'staging' ]]; then
              echo ::set-output name=domain::playground-staging
          fi
        env:
          ENV: ${{ matrix.env }}

      - name: Audit URLs using Lighthouse
        uses: foo-software/lighthouse-check-action@v7.1.1
        with:
          urls: https://${{ steps.env.outputs.domain }}.substrate.dev/

      - uses: microsoft/playwright-github-action@v1.5.1

      - name: Run tests
        run: yarn && yarn test
        working-directory: ./e2e
        timeout-minutes: 3
        env:
          ENV: ${{ matrix.env }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
