#
# Continuously tests (every 30 minutes) staging and production environment using e2e tests.
#
name: Continuous Testing playground

on:
  workflow_dispatch:
  pull_request:
    branches:
    - develop
    paths:
    - '.github/workflows/ct-playground.yml'
    - 'e2e/**'
  schedule:
    - cron:  '0 * * * *' # Every hour

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env: [production]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop

      - name: Setup node
        uses: actions/setup-node@v3.5.1
        with:
          node-version: "16"

      - uses: microsoft/playwright-github-action@v1.5.4

      - name: Run tests
        run: yarn && yarn test
        working-directory: ./e2e
        timeout-minutes: 5
        env:
          ENV: ${{ matrix.env }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
