name: Continuous Testing playground

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/30 * * * *' # Every 30 minutes

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [staging, production]
      max-parallel: 1
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Set environment
        id: env
        run: |
          if [[ $ENV == 'production' ]]; then
              echo ::set-output name=domain::playground
          elif [[ $ENV == 'staging' ]]; then
              echo ::set-output name=domain::playground-staging
          fi
        env:
          ENV: ${{ matrix.env }}

      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@7.0.0
        with:
          urls: https://${{ steps.env.outputs.domain }}.substrate.dev/

      - uses: microsoft/playwright-github-action@v1.5.0

      - name: Run tests
        run: yarn && yarn test
        working-directory: ./e2e
        continue-on-error: true
        timeout-minutes: 3
        env:
          ENV: ${{ matrix.env }}

      - if: ${{ failure() }}
        uses: s3krit/matrix-message-action@v0.0.3
        with:
          room_id: ${{ secrets.MATRIX_ROOM_ID }}
          access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
          message: "Integration tests failed"
          server: "matrix.parity.io"
