name: Continuous Testing Playground

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/30 * * * *' # Every 30 minutes

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [staging, production]
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2-beta
        with:
          node-version: "14"

      - uses: microsoft/playwright-github-action@v1

      - name: Run tests
        run: yarn && yarn test
        working-directory: ./e2e
        env:
          ENVIRONMENT: ${{ matrix.env }}

      - if: ${{ failure() }}
        uses: s3krit/matrix-message-action@v0.0.3
        with:
          room_id: ${{ secrets.MATRIX_ROOM_ID }}
          access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
          message: "Integration tests failed"
          server: "matrix.parity.io"

      - if: ${{ failure() }}
        name: Create Issue
        uses: peter-evans/create-issue-from-file@v2
        with:
          title: Integration tests failed
          content-filepath: ./templates/ct-issue.md
          labels: report, automated issue
          assignees: jeluard